### PR TITLE
demo changes

### LINKED ISSUE #1: New issue
This is an issue about @bucketheaded 

Steps to reproduce

- do this
- do this

### PR DESCRIPTION
**Pull request by ismailsahal**
yes

### CODE REVIEW

File: src/main/java/helloworld/HelloWorld.java [hunk 1]
```diff
@@ -3,7 +3,7 @@
 public class HelloWorld {
     public static void main(String[] args) {
 
-        System.out.println("Hello World");
+        System.out.println("Hello Demo World");
```
Comment (yasinkokturk) [inline src/main/java/helloworld/HelloWorld.java]:
```suggestion
        System.out.println("Hello Demo World lol");
```
Check this out.

**Review by yasinkokturk — CHANGES_REQUESTED** [review]
This is my review.
